version: "3.7"
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    image: playground-ds
    stdin_open: true
    tty: true
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=playground
    volumes:
      - ${PWD}:/home/jovyan/work
    ports:
      - 8000:8888
    container_name: playground
